name: Pico MSC Build Action
on:
  push:
  workflow_dispatch:

jobs:
    test_build:
        name: Build Pico MSC program
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
          - name: Clean workspace
            run: |
              echo "Cleaning up previous run"
              rm -rf "${{ github.workspace }}"
              mkdir -p "${{ github.workspace }}"

          - name: Checkout
            uses: actions/checkout@v4
            with:
              path: Pico-MSC

          - name: Checkout pico-sdk/develop
            uses: actions/checkout@v4
            with:
              repository: raspberrypi/pico-sdk
              ref: 2.0.0
              path: pico-sdk

          - name: Checkout pico-sdk submodules
            working-directory: ${{github.workspace}}/pico-sdk
            run: git submodule update --init

          - name: Install dependencies
            run: |
              sudo apt-get install cmake ninja-build
              # install gcc cross-compile for ARM v 13.3.1
              curl -Lo gcc-arm-none-eabi.tar.xz "https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi.tar.xz"
              sudo mkdir /opt/gcc-arm-none-eabi
              sudo tar xf gcc-arm-none-eabi.tar.xz --strip-components=1 -C /opt/gcc-arm-none-eabi
              echo 'export PATH=$PATH:/opt/gcc-arm-none-eabi/bin' | sudo tee -a /etc/profile.d/gcc-arm-none-eabi.sh
              export PATH=$PATH:/opt/gcc-arm-none-eabi/bin
              export PICO_TOOLCHAIN_PATH=/opt/gcc-arm-none-eabi/bin
              source /etc/profile
              ls -lrta /opt/gcc-arm-none-eabi/bin
              arm-none-eabi-c++ --version

          - name: Build Project
            working-directory: ${{github.workspace}}/Pico-MSC
            # bash required otherwise this mysteriously (no error) fails at "Generating cyw43_bus_pio_spi.pio.h"
            shell: bash
            run: |
              echo ${{ github.ref }}
              mkdir build
              cd build
              cmake .. -G "Ninja" -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/opt/gcc-arm-none-eabi/bin/arm-none-eabi-gcc -DCMAKE_CXX_COMPILER:FILEPATH=/opt/gcc-arm-none-eabi/bin/arm-none-eabi-g++ -DPICO_TOOLCHAIN_PATH=/opt/gcc-arm-none-eabi/bin -DPICO_SDK_PATH=../../pico-sdk -DCMAKE_BUILD_TYPE=Release -DPICO_BOARD=pico
              cmake --build .
              cd ..
              ls -lrt build/*.uf2

          - name: Upload Build Artifacts
            uses: actions/upload-artifact@v4
            with:
                name: workspace_artifacts
                path: ${{steps.build.outputs.output_dir}}
                if-no-files-found: error
