name: Pico MSC Build Action
on:
  push:
  workflow_dispatch:

jobs:
    test_build:
        name: Build Pico MSC Firmware
        runs-on: ubuntu-latest
        permissions:
          contents: write
          repository-projects: write

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Build Pico MSC Firmware
            id: build
            uses: samyarsadat/Pico-Build-Action@v1
            with:
                source_dir: "."
                output_dir: "build"
                output_ext: "*.uf2 *.elf *.elf.map *.hex *.bin *.dis"
                cmake_args: "-DCMAKE_BUILD_TYPE=Debug"

          - name: Deploy Nightly Development Release
            uses: pyTooling/Actions/releaser@r0
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
              tag: nightly_build
              files: build/*.uf2

          - name: Upload Build Artifacts
            uses: actions/upload-artifact@v4
            with:
                name: workspace_artifacts
                path: ${{steps.build.outputs.output_dir}}
                if-no-files-found: error