name: Pico MSC Nightly Build Action
on:
  push:
  workflow_dispatch:

jobs:
    nightly_build:
        name: Nightly Build a Pico Firmware
        runs-on: ubuntu-latest
        permissions:
          contents: write
          repository-projects: write

        steps:
          - name: Checkout the Pico Project Repository
            uses: actions/checkout@v4

          - name: Build the Pico Firmware
            id: build
            uses: samyarsadat/Pico-Build-Action@v1
            with:
                source_dir: "."
                output_dir: "build"
                output_ext: "*.uf2"
                cmake_args: "-DCMAKE_BUILD_TYPE=Debug"

          - name: Deploy a Nightly Build Release
            uses: pyTooling/Actions/releaser@r0
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
              tag: nightly_build
              files: build/*.uf2
